#ifndef GUARD_TENDERBATCHPROCESSING_INFRASTRUCTURE_ACCESSOR_OMGSUPPLIERCALCACC_H
#define GUARD_TENDERBATCHPROCESSING_INFRASTRUCTURE_ACCESSOR_OMGSUPPLIERCALCACC_H

#include <libutil/accessor.h>

namespace tenderbatchprocessing
{
namespace infrastructure
{
namespace accessor
{
namespace omgsuppliercalc
{
	BEGIN_QUERY_BUILDER_DECLARATION( SelectOMGCalcForTransfer )
	END_BUILDER_DECLARATION

	BEGIN_WRITE_BUILDER_DECLARATION( InsertOMGSupplierCalc)
	END_BUILDER_DECLARATION

	BEGIN_WRITE_BUILDER_DECLARATION( UpdateOMGSupplierCalcTransferred )
	END_BUILDER_DECLARATION
}
}
}
}

#endif //end GUARD_TENDERBATCHPROCESSING_INFRASTRUCTURE_ACCESSOR_OMGSUPPLIERCALCACC_H
