//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by presentation.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_VIEW_MAIN                   101
#define IDR_MAINFRAME                   128
#define IDR_presentationTYPE            129
#define IDS_VIEW_USER_LI_ID             129
#define IDS_VIEW_USER_LI_USERNAME       130
#define IDD_DLG_USR_DTL                 131
#define IDS_MSG_OK                      131
#define IDS_APP_USER                    132
#define IDD_DLG_ABOUT                   132
#define IDS_APP_CONNECT                 133
#define IDS_APP_CONNECT_TRY             134
#define ID_INDICATOR_USERNAME           135
#define ID_INDICATOR_CONNECT            136
#define IDC_CURSOR_HAND                 136
#define IDS_INDICATOR_CONNECT           137
#define IDS_INDICATOR_USER              138
#define IDD_DLG_USR_LST                 138
#define IDS_MENUMSG_QUESTION_DOKUMENTATION 139
#define IDS_DOKU_URL                    140
#define IDS_APP_DATUMZEIT               141
#define IDS_CANCEL                      142
#define IDS_DETAIL                      143
#define IDS_SAVE                        144
#define IDS_ACTIV                       145
#define IDS_CHANGEPW                    146
#define IDS_USERNAME                    147
#define IDD_DLG_GRP                     147
#define IDS_PASSWORD                    148
#define IDD_DLG_GRP_USER                148
#define IDS_SURNAME                     149
#define IDD_DLG_ADM_USR_RIGHTS          149
#define IDS_FORENAME                    150
#define IDS_DESC                        151
#define IDD_DLG_DLL_APP_MOD_RIGHT       151
#define IDS_MAIL                        152
#define IDD_DLG_APP_DTL                 152
#define IDS_EMAIL                       153
#define IDD_DLG_MOD_DTL                 153
#define IDS_LASTLOG                     154
#define IDD_DLG_RIGHT_DTL               154
#define IDS_DLG_USR_DTL                 155
#define IDD_DLG_DLL_BRANCH_REG          155
#define IDS_DLG_USR_LST                 156
#define IDD_DLG_BRANCH_REG_DTL          156
#define IDS_APP_NAME                    157
#define IDD_DLG_COR_BR_REG              157
#define IDS_MF_FILE                     158
#define IDD_DLG_DLL_GROUP               158
#define IDS_APP_LI_APPNAME              159
#define IDD_DLG_GROUP_DTL               159
#define IDS_ERR_UNAME                   160
#define IDD_DLG_DLL_LANG_TEXT           160
#define IDS_ERR_PW                      161
#define IDD_DLG_DTL_LANG                161
#define IDS_ERR_UNAME_EXISTS            162
#define IDD_DLG_DLL_TEXTE               162
#define IDS_ERR_SQL_COUNT_UNAME         163
#define IDD_DLG_DTL_TEXT                163
#define IDS_ERR_GETDLGDATA              164
#define IDD_DLG_DLL_PARA                164
#define IDS_ERR_UPDATE                  165
#define IDD_DLG_DTL_PARA                165
#define IDS_ERR_INSERT                  166
#define IDD_DLG_PREVIOUS                166
#define IDS_DELETE_SURE                 167
#define IDD_DLG_PW                      167
#define IDS_YES                         168
#define IDS_MSG_YES                     168
#define IDD_DLG_RI_ANALYSIS             168
#define IDS_NO                          169
#define IDS_MSG_NO                      169
#define IDS_HEAD_SECURE                 170
#define IDI_ICON1                       170
#define IDI_ICON_NEW                    170
#define IDS_ERR_DELETE                  171
#define IDD_DLG_EXPRESS_RIGHTS          171
#define IDS_VIEW_USER_LI_SURNAME        172
#define IDD_DLG_RI_ANALOG               172
#define IDS_VIEW_USER_LI_FORENAME       173
#define IDD_DLG_BI_DEFAULT              173
#define IDS_DLG_GROUP_LI_NAME           174
#define IDD_DLG_COR_USER_GROUP          174
#define IDS_LI_ID                       175
#define IDD_DLG_USR_ANALYSIS            175
#define IDS_LI_BEZ                      176
#define IDD_DLG_USR_RIGHT_ANALYSIS      176
#define IDS_GROUP                       177
#define IDD_DLG_DLL_USERTYPES           177
#define IDS_USER                        178
#define IDD_DLG_USERTYPES_DTL           178
#define IDS_GROUPRIGHTS                 179
#define IDD_DLG_DLL_USERPARAS           179
#define IDS_ERR_APPNAME                 180
#define IDD_DLG_USERPARAS_DTL           180
#define IDS_ERR_SQL_COUNT_APPNAME       181
#define IDD_DLG_USER_MANAGER            181
#define IDS_ERR_APPNAME_EXISTS          182
#define IDS_ERR_MODID                   183
#define IDS_ERR_SQL_COUNT_MODID         184
#define IDS_ERR_MODID_EXISTS            185
#define IDS_ERR_RINAME                  186
#define IDS_ERR_SQL_COUNT_RINAME        187
#define IDS_ERR_RINAME_EXISTS           188
#define IDS_DELETE_SURE_ALL_APP         189
#define IDS_BRDTL_TITLE                 190
#define IDS_REGDTL_TITLE                191
#define IDS_BRID_VALUE                  192
#define IDS_REGID_VALUE                 193
#define IDS_ERR_BRREGNAME               194
#define IDS_ERR_BRANCHID                195
#define IDS_ERR_REGID                   196
#define IDS_ERR_SQL_COUNT_BRREGID       197
#define IDS_ERR_BRREGID_EXISTS          198
#define IDS_ALL_APP                     199
#define IDS_ERR_GRPNAME                 200
#define IDS_ERR_SQL_COUNT_GRPNAME       201
#define IDS_ERR_GRPNAME_EXISTS          202
#define IDS_ERR_LANGNAME                203
#define IDS_ERR_LANGID                  204
#define IDS_ERR_SQL_COUNT_LANGID        205
#define IDS_ERR_LANGID_EXISTS           206
#define IDS_ERR_UPDATE_BACKUP           207
#define IDS_LI_REFTEXT                  208
#define IDS_DBKONFIGURIEREN_LABEL       209
#define IDS_ERR_REFTEXT                 210
#define IDS_ERR_TEXT                    211
#define IDS_ERR_SQL_COUNT_REFTEXT       212
#define IDS_ERR_REFTEXT_EXISTS          213
#define IDS_NO_COR_TXT_EN_DEL           214
#define IDS_TEXT_EN                     215
#define IDS_SELECT_ITEM                 216
#define IDS_SET_REFTEXT_LANG            217
#define IDS_LANG_NOT_NEW                218
#define IDS_CHANGE_LANGNAME             219
#define IDS_LI_PARA1                    220
#define IDS_LI_PARA2                    221
#define IDS_LI_PARABEZ                  222
#define IDS_LI_PARAVAL                  223
#define IDS_ERR_PARABEZ                 224
#define IDS_ERR_PARAVAL                 225
#define IDS_ERR_PARA_1_2                226
#define IDS_ERR_SQL_COUNT_PARA          227
#define IDS_ERR_PARA_EXISTS             228
#define IDS_NO_RIGHT                    229
#define IDS_LOGIN_TITLE                 230
#define IDS_VERSION                     231
#define IDS_DLL_CONFIG                  232
#define IDS_ALL_GRP                     233
#define IDS_STRING234                   234
#define IDS_ALL_USR                     234
#define IDS_VIEW_PREV_LI_WINNAME        235
#define IDS_VIEW_PREV_LI_LANG           236
#define IDS_VIEW_PREV_LI_AREA           237
#define IDS_CHANGE_TO                   238
#define IDS_NO_UPDATE_POSS              239
#define IDS_UPDATED_EXTERN              240
#define IDS_NOT_ALL_DISCONN             241
#define IDS_NEW_APP                     242
#define IDS_NO_CONN                     243
#define IDS_NO_ACTIV_CONN               244
#define IDS_CHECK_PW                    245
#define IDS_USER_LOCKED                 246
#define IDS_USER_UPD_NOT_FROM_BACKUP    247
#define IDS_APP                         248
#define IDS_MOD                         249
#define IDS_RIGHT                       250
#define IDS_ANALY_FOR_ALL_USR           251
#define IDS_ANALY_FOR_SPEC_USR          252
#define IDS_PRINT_MSG                   253
#define IDS_PRINT_TITLE                 254
#define IDS_PRINT_PAGE                  255
#define IDS_PRINT_DATE                  256
#define IDS_MSG_APP_EXIT                257
#define IDS_ANALY_RIGHTS                258
#define IDS_MSG_CHANGE_HOST             259
#define IDS_USER_ONLY_READ              260
#define IDS_DBCONFIG_PARA               261
#define IDS_STRING262                   262
#define IDS_CHANGE_TO_MAINHOST          262
#define IDS_PHARMA_AG                   263
#define IDS_PHOENIX                     264
#define IDS_ERR_INSERT_NEW_RIGHT        265
#define IDS_ERR_UPDATE_APPL_RIGHT       266
#define IDS_ERR_DEL_APPL_RIGHT          267
#define IDS_GROUP_ANALOG                268
#define IDS_ERR_LOAD_GRP_ANALOG         269
#define IDS_ERR_DEL_GRP_ANALOG          270
#define IDS_ERR_INS_GRP_ANALOG          271
#define IDS_ERR_RIDESC                  272
#define IDS_EXP_USR_RIGHTS              273
#define IDS_EXP_GRP_RIGHTS              274
#define IDS_OVERWRITE                   275
#define IDS_EXP_RI_OK                   276
#define IDS_EXP_ANALOG                  277
#define IDS_ANAL_RI_USR_OK              278
#define IDS_EXP_RI_NO_ACTION            279
#define IDS_ANALYSIS_ALL_USR            280
#define IDS_MSG_NTUSER_SURNAME_EMPTY    281
#define IDS_ERR_REMARK                  282
#define IDS_ERR_COUNTRYCODE             283
#define IDS_MSG_ERR_SELCOUNT_IBIUSER    284
#define IDS_UPDATE_IBIUSER              285
#define IDS_MSG_ERR_UPD_IBIUSER         286
#define IDS_MSG_ERR_INS_IBIUSER         287
#define IDS_MSG_SAVE_FIRST              288
#define IDS_EXP_CORUSR                  289
#define IDS_EXP_CORUSR_OK               290
#define IDS_OVERWRITE_CORUSR            291
#define IDS_ERR_NO_BRANCH_INPUT         292
#define IDS_MSG_ERR_INS_IBIUSERCOUNTRYRIGHTS 293
#define IDS_MSG_ERR_SELCOUNT_IBIUSERCOUNTRYR 294
#define IDS_MSG_BIDEF_OK                295
#define IDS_GERMAN                      296
#define IDS_ENGLISH                     297
#define IDS_FRENCH                      298
#define IDS_CROATIAN                    299
#define IDS_INPUT_FOR_BIDEFAULT         300
#define IDS_ANALY_USER                  301
#define IDS_PRT_USR_ANALY_TITLE         302
#define IDS_DEL_EXPRESS                 303
#define IDS_EXISTING_GRP                304
#define IDS_EXISTING_USR                305
#define IDS_MAIN_REPORT                 306
#define IDS_VARIABLE_REPORT             307
#define IDS_ERR_PW_TOO_SHORT            308
#define IDS_ERR_PW_NOT_COMPLEX          309
#define IDS_ERR_NTUSER                  310
#define IDS_STRING311                   311
#define IDS_EXTERNAL_IDF                311
#define IDS_GROUPID                     312
#define IDS_BRANCH_NO                   313
#define IDS_ERR_USERTYPENAME            314
#define IDS_ERR_USERTYPEDESC            315
#define IDS_ERR_SQL_COUNT_USERTYPENAME  316
#define IDS_ERR_USERTYPENAME_EXISTS     317
#define IDS_DLG_USERTYPE_LI_NAME        318
#define IDS_DLG_USERTYPE_LI_ID          319
#define IDS_DLG_USERTYPE_LI_DESC        320
#define IDS_DLG_USERTYPE_LI_COUNT       321
#define IDS_DLG_USERPARA_LI_NAME        322
#define IDS_DLG_USERPARA_LI_ID          323
#define IDS_DLG_USERPARA_LI_DESC        324
#define IDS_DLG_USERPARA_LI_COUNT       325
#define IDS_ERR_USERPARANAME            326
#define IDS_ERR_USERPARADESC            327
#define IDS_ERR_SQL_COUNT_USERPARANAME  328
#define IDS_ERR_USERPARANAME_EXISTS     329
#define IDS_NO_USERS                    330
#define IDS_ERR_USERTYPE                331
#define IDS_ERR_USERCOUNTRY             332
#define IDS_ERR_PW_CHANGEFLAG           333
#define IDS_USER_COUNT                  334
#define IDS_VIEW_USER_LI_USERCOUNTRY    335
#define IDS_VIEW_USER_LI_USERTYPE       336
#define IDS_APP_USERMGR_USERID          337
#define IDS_APP_USERMGR_USERNAME        338
#define IDS_APP_USERMGR_LASTNAME        339
#define IDS_APP_USERMGR_FIRSTNAME       340
#define IDS_APP_USERMGR_USERTYPE        341
#define IDS_APP_USERMGR_COUNTRY         342
#define IDS_APP_USERMGR_GROUPID         343
#define IDS_APP_USERMGR_GROUPNAME       344
#define IDS_APP_USERMGR_BRANCH          345
#define IDS_APP_USERMGR_PARAMNAME       346
#define IDS_APP_USERMGR_PARAMVALUE      347
#define IDC_BT_CANCEL                   1002
#define IDC_ED_UNAME                    1003
#define IDC_ED_LASTLOG                  1004
#define IDC_TXT_PRODUCT                 1005
#define IDC_ED_LASTPWCHANGE             1005
#define IDC_TXT_VER                     1006
#define IDC_TXT_VERSION                 1007
#define IDC_TXT_EXE                     1008
#define IDC_TXT_DAT                     1009
#define IDC_TXT_TIME                    1010
#define IDC_TXT_HOST                    1011
#define IDC_TXT_DB                      1012
#define IDC_TXT_DATE                    1013
#define IDC_TXT_HOSTNAME                1014
#define IDC_TXT_DATABASE                1015
#define IDC_TXT_DOKU                    1016
#define IDC_TXT_URL                     1017
#define IDC_TXT_DLL                     1018
#define IDC_TXT_COPYRIGHT               1019
#define IDC_BT_OK                       1021
#define IDC_LI_DLLS                     1022
#define ID_PIC_COMPANY                  1023
#define IDC_LST_USER                    1024
#define IDC_BT_USREXIT                  1026
#define IDC_TXT_USERNAME                1027
#define IDC_TXT_PASSWORD                1028
#define IDC_TXT_SURNAME                 1029
#define IDC_TXT_FORENAME                1030
#define IDC_TXT_DESC                    1031
#define IDC_TXT_MAIL                    1032
#define IDC_TXT_FORENAME2               1032
#define IDC_TXT_USERTYPESEL             1032
#define IDC_TXT_EMAIL                   1033
#define IDC_TXT_EMAIL2                  1034
#define IDC_TXT_FORENAME3               1034
#define IDC_TXT_COUNTRYSEL              1034
#define IDC_TXT_USERTYPE                1035
#define IDC_TXT_DESC2                   1035
#define IDC_TXT_REFERENCE               1035
#define IDC_ED_PASSWORD                 1036
#define IDC_TXT_DESC3                   1036
#define IDC_TXT_EXTERNAL                1036
#define IDC_ED_SURNAME                  1037
#define IDC_TXT_DESC4                   1037
#define IDC_TXT_PWDCHANGE               1037
#define IDC_EDFORENAME                  1038
#define IDC_TXT_SURNAME2                1038
#define IDC_TXT_PWDCHANGEDATE           1038
#define IDC_ED_DESCRIPTION              1039
#define IDC_TXT_DESC5                   1039
#define IDC_TXT_PWDCRYPT                1039
#define IDC_ED_MAIL                     1040
#define IDC_TXT_SURNAME3                1040
#define IDC_TXT_LOGINDATE               1040
#define IDC_ED_EMAIL                    1041
#define IDC_TXT_USERACTIVE              1041
#define IDC_CHECK_ACTIV                 1042
#define IDC_CHECK_CHANGEPW              1043
#define IDC_BT_SAVE                     1044
#define IDC_TXT_LASTLOG                 1045
#define IDC_TXT_LASTLOG2                1046
#define IDC_CHECK_EXTERNAL              1047
#define IDC_LI_GROUP                    1048
#define IDC_ED_REFERENCE                1048
#define IDC_COMBO_APP_GRP               1049
#define IDC_TXT_USERCOUNTRY             1049
#define IDC_BT_USRNEW                   1050
#define IDC_BT_USRDEL                   1051
#define IDC_LI_APP_USR                  1053
#define IDC_TXT_SELAPP                  1054
#define IDC_BT_SELAPP                   1055
#define IDC_BT_ALLAPP                   1056
#define IDC_BT_USR_DETAIL               1059
#define IDC_LI_APP_GRP                  1060
#define IDC_BT_SEL_APP                  1061
#define IDC_BT_SEL_GROUP                1063
#define IDC_BT_NEW_GROUP                1064
#define IDC_LI_USR_COR                  1065
#define IDC_LI_USR_ALL                  1066
#define IDC_TXT_GROUP                   1067
#define IDC_BT_GRP_COR_USR              1068
#define IDC_BT_GRP_COR_DEL              1069
#define IDC_BT_EXIT_GRPCOR              1070
#define IDC_LI_ADM_APP                  1071
#define IDC_LI_ADM_MODULE               1072
#define IDC_LI_ADM_BRANCH               1073
#define IDC_LI_ADM_USR                  1074
#define IDC_TXT_USRGRP                  1075
#define IDC_LI_ADM_COR_RIGHTS           1076
#define IDC_LI_ADM_ALLRIGHTS            1077
#define IDC_BT_CORRIGHT                 1078
#define IDC_BT_ERASERIGHT               1079
#define IDC_BT_ADM_EXIT                 1080
#define IDC_BT_ADM_APP                  1081
#define IDC_BT_ADM_MOD                  1082
#define IDC_BT_ADM_BRANCH               1083
#define IDC_BT_ADM_USR                  1085
#define IDC_LI_ADM_REG                  1087
#define IDC_BT_REG                      1088
#define IDC_LI_ADM_GROUPRIGHTS          1089
#define IDC_TXT_GROUPRIGHTS             1090
#define IDC_LI_DLL_APP                  1092
#define IDC_BT_DLL_APP_SEL              1093
#define IDC_BT_DLL_APP_NEW              1094
#define IDC_BT_DLL_APP_WORK             1095
#define IDC_BT_DLL_APP_DEL              1096
#define IDC_LI_DLL_MOD                  1097
#define IDC_BT_DLL_MOD_SEL              1098
#define IDC_BT_DLL_MOD_NEW              1099
#define IDC_BT_USRANALY_SEL_RI          1099
#define IDC_BT_DLL_MOD_WORK             1100
#define IDC_BT_DLL_MOD_DEL              1101
#define IDC_BT_DLL_APP_EXIT             1102
#define IDC_LI_DLL_RIGHTS               1103
#define IDC_BT_APP_EXIT                 1104
#define IDC_BT_DLL_RI_NEW               1105
#define IDC_BT_APP_SAVE                 1105
#define IDC_BT_DLL_RI_WORK              1106
#define IDC_ED_APPID                    1106
#define IDC_BT_DLL_RI_DEL               1107
#define IDC_ED_APPNAME                  1107
#define IDC_ED_APPDESC                  1108
#define IDC_ED_MOD_APPID                1109
#define IDC_ED_MODID                    1110
#define IDC_ED_MODNAME                  1111
#define IDC_BT_MOD_SAVE                 1112
#define IDC_BT_MOD_EXIT                 1113
#define IDC_ED_RI_APPNAME               1114
#define IDC_ED_RI_MODNAME               1115
#define IDC_ED_RINAME                   1116
#define IDC_ED_RIDESC                   1117
#define IDC_BT_RI_SAVE                  1118
#define IDC_BT_RI_EXIT                  1119
#define IDC_LI_BREG_APP                 1120
#define IDC_BT_BRREG_APP                1121
#define IDC_LI_BRREG_COR_BR             1122
#define IDC_LI_BRREG_ALL_BR             1123
#define IDC_BT_BRREG_COR_BR             1124
#define IDC_BT_BRREG_ERASE_BR           1125
#define IDC_BT_BRREG_NEW_BR             1126
#define IDC_BT_BRREG_WORK_BR            1127
#define IDC_BT_BRREG_DEL_BR             1128
#define IDC_BT_BRREG_EXIT               1129
#define IDC_LI_BREG_COR_REG             1130
#define IDC_LI_BRREG_ALL_REG            1131
#define IDC_BT_BRREG_COR_REG            1132
#define IDC_BT_BRREG_ERASE_REG          1133
#define IDC_BT_BRREG_NEW_REG            1134
#define IDC_BT_BRREG_WORK_REG           1135
#define IDC_BT_BRREG_DEL_REG            1136
#define IDC_BT_BRREG_COR                1137
#define IDC_BUTTON14                    1138
#define IDC_BT_RI_ANALY_ALL_USR         1138
#define IDC_BT_RI_ANALY_SEL_RIGHTS      1138
#define IDC_ED_ID                       1140
#define IDC_ED_NAME                     1141
#define IDC_BT_BRREG_SAVE               1142
#define IDC_TXT_IDVALUE                 1144
#define IDC_ED_APP                      1145
#define IDC_ED_REG                      1146
#define IDC_LI_BR_COR                   1147
#define IDC_LI_BR_ALL                   1148
#define IDC_BT_BR_COR                   1149
#define IDC_BT_BR_ERASE                 1150
#define IDC_BT_BRCOR_EXIT               1151
#define IDC_EDIT1                       1152
#define IDC_ED_GRP_COR_USR_APP          1152
#define IDC_ED_PW                       1152
#define IDC_ED_NTUSER                   1152
#define IDC_ED_BIDEF_NTUSER             1152
#define IDC_ED_FILTER_USERID            1152
#define IDC_EDT_FILTER_USERID           1152
#define IDC_BT_WORK_COR_REG             1153
#define IDC_ED_NTUSER2                  1153
#define IDC_EDT_NTUSER                  1153
#define IDC_BT_WORK_COR_BR              1154
#define IDC_LI_DLL_GRP                  1154
#define IDC_ED_NTUSER3                  1154
#define IDC_EDT_DESC                    1154
#define IDC_ED_NTUSER4                  1155
#define IDC_EDT_REFERENCE               1155
#define IDC_BT_GRP_NEW                  1156
#define IDC_BT_GRP_WORK                 1157
#define IDC_BT_GRP_DEL                  1158
#define IDC_BT_GRP_RIGHTS               1159
#define IDC_BT_GRP_SAVE                 1160
#define IDC_ED_GRP_NAME                 1162
#define IDC_BT_GRP_EXIT                 1163
#define IDC_ED_GRP_ID                   1164
#define IDC_BT_GRP_DTL_EXIT             1165
#define IDC_BT_GRP_DLL_EXIT             1166
#define IDC_LI_LANG_TEXT_APP            1167
#define IDC_BT_LANG_TEXT_SEL_APP        1168
#define IDC_LI_LANG_COR                 1169
#define IDC_LI_LANG_ALL                 1170
#define IDC_BT_LANG_COR                 1171
#define IDC_BT_LANG_ERASE               1172
#define IDC_BT_LANG_NEW                 1173
#define IDC_BT_LANG_WORK                1174
#define IDC_BT_LANG_DEL                 1175
#define IDC_BT_WORK_CORLANG             1176
#define IDC_BT_LANG_TEXT_EXIT           1178
#define IDC_ED_LANG_NAME                1179
#define IDC_BT_LANGDTL_SAVE             1180
#define IDC_BT_LANGDTL_EXIT             1181
#define IDC_ED_LANG_ID                  1182
#define IDC_LI_TXT_LANG                 1190
#define IDC_LI_TXT_COR                  1191
#define IDC_LI_TXT_ALL                  1192
#define IDC_BT_TEXTE_EXIT               1193
#define IDC_BT_TXT_SEL_LANG             1194
#define IDC_BT_TXT_COR                  1195
#define IDC_BT_TXT_ERASE                1196
#define IDC_BT_WORK_TXTCOR              1197
#define IDC_BT_TXT_NEW                  1198
#define IDC_BT_TXT_WORK                 1199
#define IDC_BT_TXT_DEL                  1200
#define IDC_ED_TXT_DTL_REF              1201
#define IDC_ED_TXT_DTL_TEXT_EN          1202
#define IDC_ED_TXT_DTL_TEXT             1203
#define IDC_BT_TXT_DTL_SAVE             1204
#define IDC_BT_TXT_DTL_EXIT             1205
#define IDC_ED_TXT_DTL_LANG             1206
#define IDC_TXT_MESSAGE                 1207
#define IDC_LI_PARA_APP                 1208
#define IDC_BT_PARA_APP                 1209
#define IDC_LI_PARA                     1210
#define IDC_BT_PARA_NEW                 1211
#define IDC_BT_PARA_WORK                1212
#define IDC_BT_PARA_DEL                 1213
#define IDC_BT_PARA_EXIT                1214
#define IDC_ED_PARA2                    1215
#define IDC_ED_PARABEZ                  1216
#define IDC_ED_PARAVAL                  1217
#define IDC_BT_DTL_PARA_SAVE            1218
#define IDC_BT_DTL_PARA_EXIT            1219
#define IDC_ED_PARA1                    1220
#define IDC_ED_PARA_APP                 1221
#define IDC_ST_RI_APP                   1222
#define IDC_ST_RI_MOD                   1223
#define IDC_ST_RI_BRANCH                1224
#define IDC_ST_RI_REG                   1225
#define IDC_ST_RI_ALL                   1226
#define IDC_ST_RI_COR                   1227
#define IDC_ST_APP_DTL_ID               1228
#define IDC_ST_APP_DTL_NAME             1229
#define IDC_ST_APP_DTL_DESC             1230
#define IDC_ST_BRREG_DTL_ID             1231
#define IDC_ST_BRREG_DTL_NAME           1232
#define IDC_ST_CORREG_APP               1233
#define IDC_ST_CORREG_REG               1234
#define IDC_ST_CORREG_BRCOR             1235
#define IDC_ST_CORREG_BRALL             1236
#define IDC_ST_APPMOD_APP               1237
#define IDC_ST_APPMOD_MOD               1238
#define IDC_ST_APPMOD_RI                1239
#define IDC_ST_DLL_BRREG_APP            1240
#define IDC_ST_DLL_BRREG_REGCOR         1241
#define IDC_ST_DLL_BRREG_REGALL         1242
#define IDC_ST_DLL_BRREG_BRCOR          1243
#define IDC_ST_DLL_BRREG_BRALL          1244
#define IDC_ST_LANG_APP                 1245
#define IDC_ST_LANG_LANGCOR             1246
#define IDC_ST_LANG_LANGALL             1247
#define IDC_ST_PARA_APP                 1248
#define IDC_ST_PARA_PARA                1249
#define IDC_ST_TEXT_LANG                1250
#define IDC_ST_TEXT_TXTCOR              1251
#define IDC_ST_TEXT_TXTALL              1252
#define IDC_ST_DTL_LANG_ID              1253
#define IDC_ST_DTL_LANG_DESC            1254
#define IDC_ST_DTL_PARA_APP             1255
#define IDC_ST_DTL_PARA_1               1256
#define IDC_ST_DTL_PARA_2               1257
#define IDC_ST_DTL_PARA_BEZ             1258
#define IDC_ST_DTL_PARA_VAL             1259
#define IDC_ST_DTL_TEXT_LANG            1260
#define IDC_ST_DTL_TEXT_REF             1261
#define IDC_ST_DTL_TEXT_EN              1262
#define IDC_ST_DTL_TXT_TXT              1263
#define IDC_ST_DTL_GRP_ID               1264
#define IDC_ST_DTL_GRP_NAME             1265
#define IDC_ST_GRP_APP                  1266
#define IDC_ST_GRP_GRP                  1267
#define IDC_ST_CORUSR_APP               1268
#define IDC_ST_CORUSR_GRP               1269
#define IDC_ST_CORUSR_USRCOR            1270
#define IDC_ST_CORUSR_USRALL            1271
#define IDC_ST_MOD_DTL_APP              1272
#define IDC_ST_MOD_DTL_ID               1273
#define IDC_ST_MOD_DTL_NAME             1274
#define IDC_ST_RI_DTL_APP               1275
#define IDC_ST_RI_DTL_MOD               1276
#define IDC_ST_RI_DTL_NAME              1277
#define IDC_ST_RI_DTL_DESC              1278
#define IDC_ST_USR_APP                  1279
#define IDC_ST_USR_APP_SEL              1280
#define IDC_ST_USR                      1281
#define IDC_BT_GRP_ALL_APP              1284
#define IDC_BT_APP_RIGHT_ALL_GRP        1285
#define IDC_LI_PREV                     1287
#define IDC_BT_PREV_EXIT                1288
#define IDC_BT_PREV_DEL                 1289
#define IDC_BT_PREV_APP                 1290
#define IDC_LI_APP_PREV                 1291
#define IDC_ST_PREV                     1292
#define IDC_ST_PW                       1293
#define IDC_BT_PW_OK                    1294
#define IDC_BT_PW_EXIT                  1295
#define IDC_LI_ANALY_APP                1296
#define IDC_LI_ANALY_USER               1297
#define IDC_LI_ANALY_RI                 1298
#define IDC_BT_ANALY_EXIT               1299
#define IDC_BT_ANALY_PRINT              1300
#define IDC_BT_ANALY_SEL_APP            1301
#define IDC_BT_ANALY_SEL_USR            1302
#define IDC_ST_ANALY_APP                1303
#define IDC_BT_ANALY_SEL_REG            1303
#define IDC_ST_ANALY_USER               1304
#define IDC_BT_ANALY_SEL_BR             1304
#define IDC_ST_ANALY_RIGHTS             1305
#define IDC_ST_ANALY_DESC               1306
#define IDC_TXT_NTUSER                  1307
#define IDC_CB_APP                      1308
#define IDC_BT_ANALOG                   1309
#define IDC_LC_EXP_APP                  1310
#define IDC_CB_GRP                      1310
#define IDC_LC_EXP_MOD                  1311
#define IDC_LC_EXP_RI                   1312
#define IDC_LC_EXP_BR                   1313
#define IDC_LC_EXP_REG                  1314
#define IDC_LC_EXP_GRPUSER              1315
#define IDC_BT_EXP_APP                  1319
#define IDC_BT_EXP_MOD                  1320
#define IDC_CK_ALL_RI                   1322
#define IDC_CK_ALL_BR                   1323
#define IDC_CK_ALL_REG                  1324
#define IDC_CK_ALL_USR                  1325
#define IDC_BT_EXP_EXIT                 1327
#define IDC_BT_ALL_GRPUSR               1329
#define IDC_ST_GRP_USR                  1330
#define IDC_BT_EXP_SAVE_RIGHTS          1331
#define IDC_CK_ALL_USRGRP               1332
#define IDC_CK_OVERWRITE                1333
#define IDC_BT_EXP_DEL_RIGHTS           1334
#define IDC_LC_ANAL_APP                 1335
#define IDC_LC_ANAL_MOD                 1336
#define IDC_CK_ALL_MOD                  1337
#define IDC_LC_ANAL_BR                  1338
#define IDC_CB_ANAL_REG_BR              1339
#define IDC_CB_ANAL_USR_GRP             1340
#define IDC_LC_ANAL_GRP                 1342
#define IDC_BT_ANAL_SAVE                1343
#define IDC_BT_ANAL_EXIT                1344
#define IDC_BT_ALL_USRGRP               1345
#define IDC_LC_ANAL_REG                 1346
#define IDC_LC_ANAL_USR                 1347
#define IDC_BT_ANAL_APP                 1348
#define IDC_BT_ANAL_MOD                 1349
#define IDC_BT_BI_DEFAULT               1351
#define IDC_ED_BIDEF_SURNAME            1352
#define IDC_ED_BIDEF_FORENAME           1353
#define IDC_ED_BIDEF_REMARK             1354
#define IDC_ED_BIDEF_BRANCH             1355
#define IDC_ED_BIDEF_COUNTRY            1356
#define IDC_ED_BIDEF_REMARK2            1356
#define IDC_ED_BIDEF_EMAIL              1356
#define IDC_ED_BIDEF_FORMAT             1357
#define IDC_ED_BIDEF_STYLE              1358
#define IDC_BT_BIDEFAULT_SAVE           1359
#define IDC_BT_BIDEFAULT_CANCEL         1360
#define IDC_LI_EXPCOR_APP               1361
#define IDC_LI_EXPCOR_GRP               1362
#define IDC_LI_EXPCOR_USR               1363
#define IDC_BT_EXPCOR_ALLGRP            1364
#define IDC_BT_EXPCOR_ALLUSR            1365
#define IDC_BT_EXPCOR_SAVE              1366
#define IDC_BT_EXPCOR_EXIT              1367
#define IDC_BT_EXPCOR_SEL_APP           1368
#define IDC_EXPCOR_CK_OVERWRITE         1370
#define IDC_BT_IBI_COUNTRYR             1371
#define IDC_CB_LANG_APPNAME             1372
#define IDC_CB_LANG_MODNAME             1372
#define IDC_CB_LANG_RIGHTDESC           1373
#define IDC_LI_USRANALY_APP             1374
#define IDC_CB_RIGHT_CATEGORY           1374
#define IDC_LI_USRANALY_MOD             1375
#define IDC_LI_USRANALY_RIGHT           1376
#define IDC_LI_USRANALY_USER            1377
#define IDC_BT_USRANALY_SEL_APP         1378
#define IDC_BT_USRANALY_SEL_MOD         1379
#define IDC_BT_USRANALY_PRINT           1380
#define IDC_BT_USRANALY_EXIT            1381
#define IDC_LC_ANALY_REG                1382
#define IDC_LC_ANALY_BR                 1383
#define IDC_ST_RIGHT_CATEGORY           1384
#define IDC_CB_BIDEF_COUNTRY            1385
#define IDC_BT_USR_RIGHT_ANALY_SEL_APP  1386
#define IDC_BT_USR_RIGHT_ANALY_SEL_USER 1388
#define IDC_BT_USR_RIGHT_ANALY_PRINT    1389
#define IDC_BT_USR_RIGHT_ANALY_EXIT     1390
#define IDC_LI_USR_RIGHT_ANALY_USER_GROUP 1391
#define IDC_LI_USR_RIGHT_ANALY_USER     1392
#define IDC_LI_USR_RIGHT_ANALY_APP      1394
#define IDC_RAD_USER_GROUP              1395
#define IDC_RAD_USER_RIGHT              1396
#define IDC_LI_USR_RIGHT_ANALY_USER_RIGHT 1398
#define IDC_USER_RIGHT_ANALY_RESULT     1399
#define IDC_RAD_ANALY_BY_APP            1400
#define IDC_RADIO2                      1401
#define IDC_RAD_ANALY_BY_USER           1401
#define ID_GB_ANALYSE_BY                1402
#define ID_GB_USR_GRP_RI_USER           1403
#define ID_GB_USR_GRP_RI_OPTION         1404
#define IDC_CB_UR_BR                    1405
#define IDC_BT_TYPE_NEW                 1406
#define IDC_BT_USERTYPE_NEW             1406
#define IDC_BT_USERTYPE_WORK            1407
#define IDC_BT_USERTYPE_DEL             1408
#define IDC_LI_DLL_USERTYPE             1409
#define IDC_ST_DTL_USERTYPE_NAME        1410
#define IDC_ED_USERTYPE_NAME            1411
#define IDC_ED_USERTYPE_ID              1412
#define IDC_ST_DTL_USERTYPE_ID          1413
#define IDC_BT_USERTYPE_SAVE            1414
#define IDC_BT_USERTYPE_DTL_EXIT        1415
#define IDC_ST_DTL_USERTYPE_DESC        1416
#define IDC_BT_USERTYPE_DLL_EXIT        1416
#define IDC_ED_USERTYPE_DESC            1417
#define IDC_LI_DLL_USERPARA             1417
#define IDC_BT_USERPARA_NEW             1418
#define IDC_BT_USERPARA_WORK            1419
#define IDC_BT_USERPARA_DEL             1420
#define IDC_BT_USERPARA_DLL_EXIT        1421
#define IDC_ST_DTL_USERPARA_ID          1422
#define IDC_ED_USERPARA_ID              1423
#define IDC_BT_USERPARA_SAVE            1424
#define IDC_ST_DTL_USERPARA_NAME        1425
#define IDC_ED_USERPARA_NAME            1426
#define IDC_BT_USERPARA_DTL_EXIT        1427
#define IDC_ST_DTL_USERPARA_DESC        1428
#define IDC_ED_USERPARA_DESC            1429
#define IDC_CB_USERTYPE                 1430
#define IDC_LST_USERS                   1431
#define IDC_CB_USERCOUNTRY              1431
#define IDC_ED_FILTER_USERNAME          1432
#define IDC_EDT_FILTER_USERNAME         1432
#define IDC_ED_FILTER_LASTNAME          1433
#define IDC_EDT_FILTER_SURNAME          1433
#define IDC_ED_FILTER_FIRSTNAME         1434
#define IDC_EDT_FILTER_FORENAME         1434
#define IDC_ED_FILTER_USERTYPE          1435
#define IDC_EDT_FILTER_USERTYPE         1435
#define IDC_ED_FILTER_COUNTRY           1436
#define IDC_EDT_FILTER_COUNTRY          1436
#define IDC_EDIT7                       1437
#define IDC_EDT_USERNAME                1437
#define IDC_EDIT8                       1438
#define IDC_EDT_PASSWORD                1438
#define IDC_EDIT9                       1439
#define IDC_EDT_SURNAME                 1439
#define IDC_EDIT10                      1440
#define IDC_EDT_FORENAME                1440
#define IDC_COMBO1                      1441
#define IDC_CMB_USERTYPESEL             1441
#define IDC_COMBO2                      1442
#define IDC_CMB_COUNTRYSEL              1442
#define IDC_EDIT11                      1443
#define IDC_EDT_EMAIL                   1443
#define IDC_EDIT12                      1444
#define IDC_EDT_USERID                  1444
#define IDC_CHECK1                      1445
#define IDC_CHK_EXTERNAL                1445
#define IDC_CHECK2                      1446
#define IDC_CHK_PWDCHANGE               1446
#define IDC_EDIT13                      1447
#define IDC_EDT_PWDCHANGEDATE           1447
#define IDC_CHECK3                      1448
#define IDC_CHK_CRYPTPHX                1448
#define IDC_CHECK4                      1449
#define IDC_CHK_CRYPTAES                1449
#define IDC_EDIT14                      1450
#define IDC_EDT_LOGINDATE               1450
#define IDC_BUTTON1                     1451
#define IDC_BTN_NEW_USER                1451
#define IDC_BUTTON2                     1452
#define IDC_BTN_SAVE_USER               1452
#define IDC_BUTTON3                     1453
#define IDC_BTN_DELETE_USER             1453
#define IDC_BTN_REFRESH_USERLIST        1454
#define IDC_BUTTON5                     1455
#define IDC_BTN_REPORT_USERS            1455
#define IDC_COMBO3                      1456
#define IDC_CMB_APPLICATIONSEL          1456
#define IDC_EDIT15                      1457
#define IDC_EDT_FILTER_ALLGROUPNAME     1457
#define IDC_LIST2                       1458
#define IDC_LST_ALLGROUPS               1458
#define IDC_LI_USERROLES                1458
#define IDC_EDIT16                      1459
#define IDC_EDT_FILTER_ALLGROUPID       1459
#define IDC_BUTTON6                     1460
#define IDC_BTN_PERMITGROUP             1460
#define IDC_BUTTON7                     1461
#define IDC_BTN_REVOKEGROUP             1461
#define IDC_LIST3                       1462
#define IDC_LST_USERGROUPS              1462
#define IDC_BUTTON8                     1463
#define IDC_BTN_COPYFROMUSER            1463
#define IDC_LIST4                       1464
#define IDC_LST_USERPARAMS              1464
#define IDC_EDIT17                      1465
#define IDC_EDT_FILTER_BRANCH           1465
#define IDC_EDIT18                      1466
#define IDC_EDT_FILTER_PARAMETER        1466
#define IDC_EDIT19                      1467
#define IDC_EDT_FILTER_VALUE            1467
#define IDC_EDIT20                      1468
#define IDC_EDT_PARAMETERVALUE          1468
#define IDC_BUTTON9                     1469
#define IDC_BTN_NEW_USERPARAM           1469
#define IDC_BUTTON10                    1470
#define IDC_BTN_SAVE_USERPARAM          1470
#define IDC_BUTTON11                    1471
#define IDC_BTN_DELETE_USERPARAM        1471
#define IDC_CHK_USERACTIVE              1472
#define IDC_BUTTON13                    1473
#define IDC_BTN_REPORT_USERGROUPS       1473
#define IDC_COMBO4                      1474
#define IDC_CMB_BRANCHSEL               1474
#define IDC_COMBO5                      1475
#define IDC_CMB_PARAMETERSEL            1475
#define IDC_EDIT21                      1476
#define IDC_EDT_FILTER_USERGROUPNAME    1476
#define IDC_EDIT22                      1477
#define IDC_EDT_FILTER_USERGROUPID      1477
#define IDC_GRP_USERLIST                1478
#define IDC_GRP_USERDETAILS             1479
#define IDC_GRP_USERAPPRELATIONS        1480
#define IDC_TXT_USERID                  1481
#define IDC_TXT_APPLICATION             1482
#define IDC_TXT_ALLGROUPS               1483
#define IDC_TXT_USERGROUPS              1484
#define IDC_TXT_APPLICATION2            1485
#define IDC_TXT_APPLICATION3            1486
#define IDC_TXT_APPLICATION4            1487
#define IDC_DELIMITER1                  1488
#define IDC_DELIMITER2                  1489
#define IDC_TXT_USERCOUNT               1490
#define IDC_GRP_DOCUMENTATION           1491
#define IDC_GRP_USER                    1492
#define IDC_GRP_APPLICATION             1494
#define IDC_GRP_DLLS                    1495
#define IDC_TXT_USER                    1496
#define IDC_TXT_ROLE                    1497
#define IDC_BTN_USERMANAGER_EXIT        1498
#define IDC_TXT_APP_BRANCH_USER_PARAMS  1499
#define ID_INFO_DOKU                    32771
#define ID_INFO_ABOUT                   32772
#define ID_DLL_DB                       32776
#define ID_ADM_USER                     32780
#define IDS_ADM_USER                    32780
#define ID_ADM_GROUP                    32781
#define IDS_ADM_GROUP                   32781
#define ID_ADM_RIGHTS                   32782
#define IDS_ADM_RIGHTS                  32782
#define ID_DLL_DOKU                     32783
#define IDS_ADM_USER_RIGHTS             32783
#define IDS_ADM_GROUP_RIGHTS            32784
#define ID_FILE                         32785
#define IDS_DB_CONFIG                   32785
#define ID_ADM                          32786
#define IDS_DLL_DOKU                    32786
#define ID_DLL                          32787
#define IDS_DBKONFIGURIEREN_APPLIKATION 32787
#define ID_INFO                         32788
#define ID_ADM_USER_RIGHTS              32791
#define ID_ADM_GROUP_RIGHTS             32792
#define ID_DBKONFIGURIEREN_APPLIKATION  32793
#define ID_DBKONFIGURIEREN_FILIALEN     32794
#define IDS_DBKONFIGURIEREN_FILIALEN    32794
#define ID_DBKONFIGURIEREN_GRUPPEN      32795
#define IDS_DBKONFIGURIEREN_GRUPPEN     32795
#define ID_DBKONFIGURIEREN_TEXTE        32796
#define IDS_DBKONFIGURIEREN_TEXTE       32796
#define ID_DBKONFIGURIEREN_PREVIOUSLOGIN 32797
#define IDS_DBKONFIGURIEREN_PREVIOUSLOGIN 32797
#define ID_DLL_CONFIG                   32798
#define IDS_INFO_ABOUT                  32798
#define ID_DB_CONFIG                    32799
#define IDS_DOKU_DLL_URL                32799
#define ID_DBKONFIGURIEREN_LABEL        32801
#define ID_DBKONFIGURIEREN_PARA         32802
#define ID_CHANGE_HOST                  32803
#define ID_Menu                         32804
#define ID_BENUTZER_RECHTE              32805
#define ID_DATEI_                       32806
#define ID_DBCONFIG_APPPARAMS           32807
#define IDS_DBCONFIG_APPPARAMS          32807
#define ID_BENUTZER_EXPRESS             32808
#define ID_EXP_USR_RIGHTS               32811
#define ID_EXPRESS_GRP_RIGHTS           32812
#define ID_EXPRESS_ANALOG               32815
#define ID_EXPRESS_COR_USER             32817
#define ID_ANALYSE_USER                 32819
#define ID_BENUTZER_USERRIGHTS          32820
#define ID_ANALYSE_USERRIGHTS           32821
#define ID_DBCONFIG_USERTYPES           32823
#define IDS_DBCONFIG_USERTYPES          32823
#define ID_DBCONFIG_USERPARAMS          32824
#define IDS_DBCONFIG_USERPARAMS         32824
#define ID_BENUTZER_BENUTZERMANAGER     32825
#define ID_USER_MANAGER                 32826
#define IDS_USER_MANAGER                32826
#define ID_GB_USR_GRP_RI_APP            65535
#define ID_GB_USRGBRI_OPTION            65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1499
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
