/****************************************************************************
 *
 *                               IBM INC.
 *
 *                           PROPRIETARY DATA
 *
 * Licensed Material - Property Of IBM
 *
 * "Restricted Materails of IBM"
 *
 * IBM Informix Client SDK
 *
 * (c)  Copyright IBM Corporation 2006,2007. All rights reserved.
 *
 *  Title:      ifxdef.h
 *  Description:
 *          This file will provide function name definations when we are using
 *          esql static library isqlt09s.lib with -static option.
 *          This has taken the data from isqli.def file.
 *
 ***************************************************************************
 */
#define  fnsqlcode ifx_sqlcode
#define  fnsqlstate ifx_sqlstate
#define ifx_getenv infx_ggetenv    
#define ifx_putenv infx_gputenv
#define  fgislct  infx__fgislct  
#define  setmsgfile  infx__setmsgfile 
#define  sqclrca  infx__sqclrca      
#define  sqg_blob  infx__sqg_blob   
#define 	a_kwcheck  infx_a_kwcheck 
#define 	bycmpr  infx_bycmpr      
#define 	bycopy  infx_bycopy     
#define 	byfill  infx_byfill    
#define 	byleng  infx_byleng   
#define 	charcmp  infx_charcmp
#define 	chkprec  infx_chkprec 
#define 	decadd  infx_decadd    
#define 	deccmp  infx_deccmp   
#define 	deccopy  infx_deccopy  
#define 	deccvasc  infx_deccvasc  
#define 	deccvdbl  infx_deccvdbl 
#define 	deccvflt  infx_deccvflt   
#define 	deccvint  infx_deccvint  
#define 	deccvlong  infx_deccvlong   
#define 	decdiv  infx_decdiv        
#define 	dececvt  infx_dececvt     
#define 	decfcvt  infx_decfcvt                                                 
#define 	decmul  infx_decmul                        
#define 	decprec  infx_decprec                     
#define 	decround  infx_decround                  
#define 	decsub  infx_decsub                     
#define 	dectoasc  infx_dectoasc                
#define 	dectodbl  infx_dectodbl               
#define 	dectoint  infx_dectoint              
#define 	dectolong  infx_dectolong           
#define 	dectrunc  infx_dectrunc            
#define 	dtcurrent  infx_dtcurrent         
#define 	dtcvasc  infx_dtcvasc            
#define 	dtcvfmtasc  infx_dtcvfmtasc     
#define 	dtextend  infx_dtextend        
#define 	dttoasc  infx_dttoasc         
#define 	dttofmtasc  infx_dttofmtasc  
#define 	incvasc  infx_incvasc       
#define 	incvfmtasc  infx_incvfmtasc
#define 	intoasc  infx_intoasc     
#define 	intofmtasc  infx_intofmtasc     
#define 	ldchar  infx_ldchar           
#define 	lddblnull  infx_lddblnull    
#define 	lddecimal  infx_lddecimal   
#define 	ldfltnull  infx_ldfltnull  
#define 	ldlong  infx_ldlong       
#define 	mmsgtext  infx_mmsgtext  
#define 	nullblobval  infx_nullblobval         
#define 	rcvarval  infx_rcvarval              
#define 	rdatestr  infx_rdatestr             
#define 	rdayofweek  infx_rdayofweek                           
#define 	rdefmtdate  infx_rdefmtdate      
#define 	rdownshift  infx_rdownshift     
#define 	rdtimestr  infx_rdtimestr      
#define 	rfmtdate  infx_rfmtdate       
#define 	rfmtdec  infx_rfmtdec        
#define 	rfmtdouble  infx_rfmtdouble   
#define 	rfmtlong  infx_rfmtlong        
#define 	rget_lmsg  infx_rget_lmsg     
#define 	rgetmsg  infx_rgetmsg        
#define 	risnull  infx_risnull       
#define 	rjulmdy  infx_rjulmdy      
#define 	rldctype  infx_rldctype   
#define 	rleapyear  infx_rleapyear   
#define 	rmdyjul  infx_rmdyjul      
#define 	rmoninit  infx_rmoninit   
#define 	rseekmsg  infx_rseekmsg  
#define 	rsetnull  infx_rsetnull   
#define 	rstrdate  infx_rstrdate    
#define 	rstrdtime  infx_rstrdtime          
#define 	rtoday  infx_rtoday                
#define 	rtosqltype  infx_rtosqltype        
#define 	rtuname  infx_rtuname             
#define 	rtypalign  infx_rtypalign        
#define 	rtypmsize  infx_rtypmsize       
#define 	rtypname  infx_rtypname        
#define 	rtypwidth  infx_rtypwidth     
#define 	rupshift  infx_rupshift      
#define 	rwildmatch  infx_rwildmatch             
#define 	sqlexit  infx_sqlexit                  
#define 	stcat  infx_stcat                    
#define 	stchar  infx_stchar                 
#define 	stchr  infx_stchr                  
#define 	stcmpr  infx_stcmpr               
#define 	stcopy  infx_stcopy              
#define 	stdblnull  infx_stdblnull       
#define 	stdecimal  infx_stdecimal      
#define 	stfltnull  infx_stfltnull     
#define 	stleng  infx_stleng          
#define 	stlong  infx_stlong         
#define 	tblobstore  infx_tblobstore 
#define 	todate  infx_todate        
#define 	todatetime  infx_todatetime     
#define 	todblnull  infx_todblnull      
#define 	tointerval  infx_tointerval   
#define 	cvtosmint  infx_cvtosmint    
#define 	fmtstr  infx_fmtstr                
#define 	rdtextend  infx_rdtextend         
#define 	rdttodate  infx_rdttodate        
#define 	rinvcopy  infx_rinvcopy         
#define 	rmsgfname  infx_rmsgfname      
#define 	rstod  infx_rstod             
#define 	rstoi  infx_rstoi            
#define 	rstol  infx_rstol           
#define 	sqgetdbs  infx_sqgetdbs    
#define 	sqlbreak  infx_sqlbreak   
#define 	sqlbreakcallback  infx_sqlbreakcallback         
#define 	sqldetach  infx_sqldetach                      
#define 	sqldone  infx_sqldone                         
#define 	sqlstart  infx_sqlstart                      
#define 	untrp  infx_untrp                           
#define 	rgetlmsg  infx_rgetlmsg                    
#define  sqhostval  infx__sqhostval               
#define  sqindhost  infx__sqindhost              
#define  sqs_  infx__sqs_                       
#define  sqs_fetch  infx__sqs_fetch            
#define  sqs_id  infx__sqs_id                 
#define  sqs_sfetch  infx__sqs_sfetch        
#define  sqseterr  infx__sqseterr           
#define  sqsetup  infx__sqsetup            
#define  sqvalhost  infx__sqvalhost       
#define 	rdataval  infx_rdataval          
#define 	rvaldata  infx_rvaldata         
#define 	dtaddinv  infx_dtaddinv        
#define 	dtsub  infx_dtsub             
#define 	dtsubinv  infx_dtsubinv      
#define 	invdivdbl  infx_invdivdbl   
#define 	invdivinv  infx_invdivinv  
#define 	invextend  infx_invextend 
#define 	invmuldbl  infx_invmuldbl             
#define 	GetConnect  infx_GetConnect          
#define 	SetConnect  infx_SetConnect         
#define 	ReleaseConnect  infx_ReleaseConnect          
#define 	fnsqlcode  ifx_sqlcode                      
#define 	fnsqlstate  ifx_sqlstate                   
#define 	fnsqlca  ifx_sqlca                        
#define 	fninetlogin  infx_inetlogin              
#define 	fntoerrno  ifx_toerrno                  
#define 	fnforkflag  ifx_forkflag               
#define 	fnrsnnumber  infx_rsnnumber           
#define 	fndbfltprec  infx_dbfltprec          
#define 	fnmonback  infx_monback             
#define 	fnmonfront  infx_monfront          
#define 	rfmtnum  infx_rfmtnum            
#define 	rinvstr  infx_rinvstr           
#define 	rstrinv  infx_rstrinv          
#define 	rtudesc  infx_rtudesc         
#define 	rvalcvar  infx_rvalcvar      
#define 	rvalstr  infx_rvalstr       
#define 	todecimal  infx_todecimal  
#define 	toint  infx_toint         
#define 	tolong  infx_tolong      
#define 	SqlFreeMem  infx_SqlFreeMem       
#define  	sqgetuser  infx_sqgetuser       
#define 	Mondecm  infx_Mondecm           
#define 	Monsep  infx_Monsep            
#define 	initlocator  infx_initlocator       
#define 	remloctmp  infx_remloctmp          
#define 	rmktemp  infx_rmktemp                                
#define 	ggetenv  infx_ggetenv           
#define 	gDecstrtoANSI  infx_gDecstrtoANSI               
#define 	fnFetArrSize  infx_fnFetArrSize                
#define 	fnFetBufSize  infx_fnFetBufSize  
#define 	fnOptMsg  infx_fnOptMsg 
#define 	dectoflt  infx_dectoflt 
#define 	ASF_Call  infx_ASF_Call 
#define 	ifx_getenv  infx_ggetenv 
#define 	ifx_putenv  infx_gputenv
#define  _fgislct  infx__fgislct       
#define  _setmsgfile  infx__setmsgfile
#define  _sqclrca  infx__sqclrca     
#define  _sqg_blob  infx__sqg_blob  
#define  a_kwcheck  infx_a_kwcheck 
#define  bycmpr  infx_bycmpr      
#define  bycopy  infx_bycopy     
#define  byfill  infx_byfill    
#define  byleng  infx_byleng   
#define  charcmp  infx_charcmp
#define  chkprec  infx_chkprec   
#define  decadd  infx_decadd    
#define  deccmp  infx_deccmp   
#define  deccopy  infx_deccopy  
#define  deccvasc  infx_deccvasc    
#define  deccvdbl  infx_deccvdbl   
#define  deccvflt  infx_deccvflt  
#define  deccvint  infx_deccvint 
#define  deccvlong  infx_deccvlong  
#define  decdiv  infx_decdiv       
#define  dececvt  infx_dececvt    
#define  decfcvt  infx_decfcvt  
#define  decmul  infx_decmul   
#define  decprec  infx_decprec   
#define  decround  infx_decround  
#define  decsub  infx_decsub     
#define  dectoasc  infx_dectoasc
#define  dectodbl  infx_dectodbl  
#define  dectoint  infx_dectoint 
#define  dectolong  infx_dectolong   
#define  dectrunc  infx_dectrunc    
#define  dtcurrent  infx_dtcurrent 
#define  dtcvasc  infx_dtcvasc    
#define  dtcvfmtasc  infx_dtcvfmtasc  
#define  dtextend  infx_dtextend     
#define  dttoasc  infx_dttoasc      
#define  dttofmtasc  infx_dttofmtasc 
#define  incvasc  infx_incvasc 
#define  incvfmtasc  infx_incvfmtasc  
#define  intoasc  infx_intoasc       
#define  intofmtasc  infx_intofmtasc    
#define  ldchar  infx_ldchar           
#define  lddblnull  infx_lddblnull    
#define  lddecimal  infx_lddecimal   
#define  ldfltnull  infx_ldfltnull  
#define  ldlong  infx_ldlong       
#define  mmsgtext  infx_mmsgtext  
#define  nullblobval  infx_nullblobval      
#define  rcvarval  infx_rcvarval           
#define  rdatestr  infx_rdatestr          
#define  rdayofweek  infx_rdayofweek     
#define  rdefmtdate  infx_rdefmtdate    
#define  rdownshift  infx_rdownshift   
#define  rdtimestr  infx_rdtimestr    
#define  rfmtdate  infx_rfmtdate     
#define  rfmtdec  infx_rfmtdec
#define  rfmtdouble  infx_rfmtdouble 
#define  rfmtlong  infx_rfmtlong    
#define  rget_lmsg  infx_rget_lmsg 
#define  rgetmsg  infx_rgetmsg    
#define  risnull  infx_risnull   
#define  rjulmdy  infx_rjulmdy  
#define  rldctype  infx_rldctype  
#define  rleapyear  infx_rleapyear    
#define  rmdyjul  infx_rmdyjul       
#define  rmoninit  infx_rmoninit    
#define  rseekmsg  infx_rseekmsg   
#define  rsetnull  infx_rsetnull  
#define  rstrdate  infx_rstrdate 
#define  rstrdtime  infx_rstrdtime    
#define  rtoday  infx_rtoday         
#define  rtosqltype  infx_rtosqltype  
#define  rtuname  infx_rtuname       
#define  rtypalign  infx_rtypalign  
#define  rtypmsize  infx_rtypmsize 
#define  rtypname  infx_rtypname  
#define  rtypwidth  infx_rtypwidth  
#define  rupshift  infx_rupshift   
#define  rwildmatch  infx_rwildmatch    
#define  sqlexit  infx_sqlexit         
#define  stcat  infx_stcat           
#define  stchar  infx_stchar        
#define  stchr  infx_stchr         
#define  stcmpr  infx_stcmpr      
#define  stcopy  infx_stcopy     
#define  stdblnull  infx_stdblnull    
#define  stdecimal  infx_stdecimal   
#define  stfltnull  infx_stfltnull  
#define  stleng  infx_stleng       
#define  stlong  infx_stlong      
#define  stbigint  infx_stbigint      
#define  ldbigint  infx_ldbigint      
#define  tblobstore  infx_tblobstore     
#define  todate  infx_todate            
#define  todatetime  infx_todatetime   
#define  todblnull  infx_todblnull    
#define  tointerval  infx_tointerval 
#define  cvtosmint  infx_cvtosmint  
#define  fmtstr  infx_fmtstr       
#define  rdtextend  infx_rdtextend
#define  rdttodate  infx_rdttodate    
#define  rinvcopy  infx_rinvcopy     
#define  rmsgfname  infx_rmsgfname  
#define  rstod  infx_rstod         
#define  rstoi  infx_rstoi       
#define  rstol  infx_rstol        
#define  sqgetdbs  infx_sqgetdbs   
#define  sqlbreak  infx_sqlbreak    
#define  sqlbreakcallback  infx_sqlbreakcallback                              
#define  sqldetach  infx_sqldetach   
#define  sqldone  infx_sqldone   
#define  sqlstart  infx_sqlstart  
#define  untrp  infx_untrp         
#define  rgetlmsg  infx_rgetlmsg    
#define  _sqhostval  infx__sqhostval 
#define  _sqindhost  infx__sqindhost   
#define  _sqs_  infx__sqs_            
#define  _sqs_fetch  infx__sqs_fetch   
#define  _sqs_id  infx__sqs_id        
#define  _sqs_sfetch  infx__sqs_sfetch 
#define  _sqseterr  infx__sqseterr    
#define  _sqsetup  infx__sqsetup     
#define  _sqvalhost  infx__sqvalhost  
#define  rdataval  infx_rdataval  
#define  rvaldata  infx_rvaldata       
#define  dtaddinv  infx_dtaddinv   
#define  dtsub  infx_dtsub    
#define  dtsubinv  infx_dtsubinv    
#define  invdivdbl  infx_invdivdbl   
#define  invdivinv  infx_invdivinv        
#define  invextend  infx_invextend   
#define  invmuldbl  infx_invmuldbl              
#define  getconnect  infx_GetConnect  
#define  setconnect  infx_SetConnect     
#define  releaseconnect  infx_ReleaseConnect    
#define  fninetlogin  infx_inetlogin                                                          
#define  fntoerrno  ifx_toerrno                                                             
#define  fnforkflag  ifx_forkflag                                                             
#define  fnrsnnumber  infx_rsnnumber                                                         
#define  fndbfltprec  infx_dbfltprec                                                          
#define  fnmonback  infx_monback                                                             
#define  fnmonfront  infx_monfront                                                            
#define  rfmtnum  infx_rfmtnum                                                                
#define  rinvstr  infx_rinvstr                                                                
#define  rstrinv  infx_rstrinv                                                                
#define  rtudesc  infx_rtudesc                                                                
#define  rvalcvar  infx_rvalcvar                                                              
#define  rvalstr  infx_rvalstr                                                                
#define  todecimal  infx_todecimal                                                            
#define  toint  infx_toint                                                                            
#define  tolong  infx_tolong                                                                          
#define  sqlfreemem  infx_SqlFreeMem                                                          
#define  _sqgetuser  infx_sqgetuser                                                           
#define  mondecm  infx_Mondecm                                                               
#define  monsep  infx_Monsep                                                                       
#define  initlocator  infx_initlocator                                               
#define  remloctmp  infx_remloctmp                                                            
#define  rmktemp  infx_rmktemp                                                                
#define  ggetenv  infx_ggetenv                                                               
#define  gDecstrtoANSI  infx_gDecstrtoANSI                                            
#define  fnFetArrSize  infx_fnFetArrSize                                              
#define  fnFetBufSize  infx_fnFetBufSize                                              
#define  dectoflt  infx_dectoflt                                                              
#define  asf_call  infx_ASF_Call  
#define  infxcexp  infx_infxcexp 
#define   ifx_getcur_conn_name   infx_ifx_getcur_conn_name                  
#define   	_ifx_getcur_conn_name   infx_ifx_getcur_conn_name        
#define   	ifx_cl_alloc   infx_ifx_cl_alloc                        
#define   	_ifx_cl_alloc   infx_ifx_cl_alloc                      
#define   	ifx_cl_dealloc   infx_ifx_cl_dealloc                  
#define   	_ifx_cl_dealloc   infx_ifx_cl_dealloc                                        
#define   	service1   getSvrInfo                                                       
#define   	service2   infx_igetint    
#define   	service3   infx_iflushbuff   
#define   	service4   infx_iwrite      
#define   	service5   infx_iputunsigned   
#define   	service6   infx_iputint       
#define   	service8   infx_igetpbuf     
#define   	service9   infx_igetlong    
#define   	service10   infx_igoblints 
#define   	service11   infx_igoblchars    
#define   	service12   infx_iputpbuf     
#define   	service13   ifx_getcur_conn  
#define   	service17   CheckGlobInit   
#define   	service14   _chktype       
#define   	service15   ifxOS_thread_mutexUnLock       
#define   	service16   ifxOS_thread_mutexLock        
#define       service18   getcur7fr9  
#define       service19   updateda7  
#define       service20   updatecur7  
#define       service21   getval9fr7 
#define       service22   getda9fr7 
#define       service23   getcur9fr7    
#define       service24   getvar9fr7   
#define       service25   copysvar9to7  
#define       service26   copycurs9to7   
#define       service27   copyda9to7    
#define       service28   copyhvar7to9 
#define       service29   getcur9     
#define       fn_xa_switch   infx_xaswitch  
#define       _fn_xa_switch   infx_xaswitch  
#define   	service30   initgls       
#define   	service31   get_glserror 
#define   	service32   rld_lmsg    
#define       sqlbreakcallback_withparams   infx_sqlbreakcallback_withparams  
#define       _sqlbreakcallback_withparams   infx_sqlbreakcallback_withparams  
#define       rtuqual   infx_rtuqual                                          
#define       _rtuqual   infx_rtuqual                                        
#define       idx_ggetenv   infx_idx_ggetenv                                
#define       _idx_ggetenv   infx_idx_ggetenv                              
#define       ifx_pam_callback   infx_ifx_pam_callback                    
#define       _ifx_pam_callback   infx_ifx_pam_callback                  
#define       rvalcvar_flag   infx_rvalcvar_flag                        
#define       _rvalcvar_flag   infx_rvalcvar_flag                      
#define       decload   infx_decload                                  
#define       _decload   infx_decload                                
#define       service33   infx_iputlong                             
#define       is_xaopened   _is_xaopened			

