//----------------------------------------------------------------------------
/*! \file
 *  \brief  intern interface BasarWidgets
 *  \author Roland Kiefert 
 *  \date   06.02.2006
 */
//----------------------------------------------------------------------------

#ifndef GUARD_LIBBASARQTWIDGET_BASARWIDGETS_H
#define GUARD_LIBBASARQTWIDGET_BASARWIDGETS_H

//--------------------------------------------------------------------------------------------------------------//
// includes
//--------------------------------------------------------------------------------------------------------------//
#pragma warning (push)
#pragma warning(disable: 4127)
#pragma warning(disable: 4512)
#include <QtDesigner/QDesignerCustomWidgetCollectionInterface>
#pragma warning (pop)

//----------------------------------------------------------------------------
/*! \brief  A class to make plugin basarwidgets. 

	This is a final class.
	This is a value class, with copying is allowed and generated by the compiler 
*/
class BasarWidgets: public QObject, 
					public QDesignerCustomWidgetCollectionInterface
{
	Q_PLUGIN_METADATA(IID "eu.phoenixgroup.BasarWidgets" FILE "basarwidgets.json")
	Q_OBJECT
    Q_INTERFACES(QDesignerCustomWidgetCollectionInterface)

public:
	/*! \brief This constructor from TableWidget \n no-throw */
	BasarWidgets	(QObject *parent = 0					//!< parent widget
					);

	/*! \brief This method give a list to all basar widget back	\n no-throw */
	virtual QList<QDesignerCustomWidgetInterface*> customWidgets() const;

private:
	QList<QDesignerCustomWidgetInterface*> widgets;		//!< list to the basar widgets
};

#endif //GUARD