//----------------------------------------------------------------------------
/*! \file
 *  \brief  intern interface plugin tablewidget
 *  \author Roland Kiefert 
 *  \date   06.02.2006
 */
//----------------------------------------------------------------------------

#ifndef GUARD_TABLEWIDGETPLUGIN_H
#define GUARD_TABLEWIDGETPLUGIN_H

//--------------------------------------------------------------------------------------------------------------//
// includes
//--------------------------------------------------------------------------------------------------------------//

#pragma warning (push)
#pragma warning(disable: 4127)  // C4127: conditional expression is constant
#pragma warning(disable: 4512)  // qobject_impl.h - C4512: 'QtPrivate::QSlotObjectBase' : assignment operator could not be generated
#include <QtDesigner/QDesignerCustomWidgetInterface>
#pragma warning (pop)

//----------------------------------------------------------------------------
/*! \brief  A class to make a plugin for the comfortable tablewidget. 

	This is a final class.
	This is a value class, with copying is allowed and generated by the compliler 
*/
class TableWidgetPlugin : public QObject, public QDesignerCustomWidgetInterface
{
    Q_OBJECT
    Q_INTERFACES(QDesignerCustomWidgetInterface)

public:
	/*! \brief This constructor from TableWidgetPlugin 
		\n     no-throw */
    TableWidgetPlugin(QObject *parent = 0						//!< parent widget
					  );

    /*! \brief Returns true if the custom widget is intended to be used as a container; otherwise returns false.
		\n     no-throw */
	bool isContainer() const;
	/*! \brief Returns true if the widget has been initialized; otherwise returns false.
		\n     no-throw */
    bool isInitialized() const;
	/*! \brief Returns the icon used to represent the custom widget in Qt Designer's widget box.
		\n     no-throw */
    QIcon icon() const;
	/*! \brief Returns the code template that Qt Designer includes in forms that contain the custom widget when they are saved.
		\n     no-throw */
    QString codeTemplate() const;
	/*! \brief Returns the name of the group to which the custom widget belongs.
		\n     no-throw */
    QString group() const;
	/*! \brief Returns the path to the include file that uic uses when creating code for the custom widget.
		\n     no-throw */
    QString includeFile() const;
	/*! \brief Returns the name of the class that implements the custom widget.
		\n     no-throw */
    QString name() const;
	/*! \brief Returns a short description of the widget that can be used by Qt Designer in a tool tip.
		\n     no-throw */
    QString toolTip() const;
	/*! \brief Returns a description of the widget that can be used by Qt Designer in "What's This?" help for the widget.
		\n     no-throw */
    QString whatsThis() const;
	/*! \brief Returns a new instance of the custom widget, with the given parent.
		\n     no-throw */
    QWidget *createWidget(QWidget *parent						//!< parent widget
						 );
	/*! \brief Initializes the widget for use with the specified formEditor interface.
		\n     no-throw */
    void initialize(QDesignerFormEditorInterface *core			//!< QDesignerFormEditorInterface * formEditor
					);

private:
    bool initialized;											//!< true if the widget has been initialized
};

#endif //GUARD
