//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UadmWebLoginService.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UadmWebLoginService.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelPW {
            get {
                return ResourceManager.GetString("ButtonCancelPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PW.
        /// </summary>
        public static string ButtonChangePW {
            get {
                return ResourceManager.GetString("ButtonChangePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is missing.
        /// </summary>
        public static string ErrorCurrentPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorCurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string ErrorFieldsRequired {
            get {
                return ResourceManager.GetString("ErrorFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Please check your credentials.
        /// </summary>
        public static string ErrorLoginFailed {
            get {
                return ResourceManager.GetString("ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is missing.
        /// </summary>
        public static string ErrorNewPassword1Required {
            get {
                return ResourceManager.GetString("ErrorNewPassword1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify password is missing.
        /// </summary>
        public static string ErrorNewPassword2Required {
            get {
                return ResourceManager.GetString("ErrorNewPassword2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different.
        /// </summary>
        public static string ErrorNewPasswordEqualOldPassword {
            get {
                return ResourceManager.GetString("ErrorNewPasswordEqualOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be at least 6 characters.
        /// </summary>
        public static string ErrorNewPasswordLength {
            get {
                return ResourceManager.GetString("ErrorNewPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords not identical.
        /// </summary>
        public static string ErrorNewPasswordVerification {
            get {
                return ResourceManager.GetString("ErrorNewPasswordVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UADM could not initialize.
        /// </summary>
        public static string ErrorResponseCouldNotInitialize {
            get {
                return ResourceManager.GetString("ErrorResponseCouldNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not verify user.
        /// </summary>
        public static string ErrorResponseCouldNotVerifyUser {
            get {
                return ResourceManager.GetString("ErrorResponseCouldNotVerifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History verify failed.
        /// </summary>
        public static string ErrorResponseHistoryVerifyFailed {
            get {
                return ResourceManager.GetString("ErrorResponseHistoryVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last password verify failed.
        /// </summary>
        public static string ErrorResponseLastPasswordVerifyFailed {
            get {
                return ResourceManager.GetString("ErrorResponseLastPasswordVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UADM connection error (LoginInterface).
        /// </summary>
        public static string ErrorResponseLoginInterfaceIsNull {
            get {
                return ResourceManager.GetString("ErrorResponseLoginInterfaceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UADM connection error (Manager).
        /// </summary>
        public static string ErrorResponseManagerIsNull {
            get {
                return ResourceManager.GetString("ErrorResponseManagerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UADM no environment found.
        /// </summary>
        public static string ErrorResponseNoEnvironmentFound {
            get {
                return ResourceManager.GetString("ErrorResponseNoEnvironmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous login data.
        /// </summary>
        public static string ErrorResponseNoPreviousLoginDataFound {
            get {
                return ResourceManager.GetString("ErrorResponseNoPreviousLoginDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password does not fit the password rules: 8-64 chars, allowed a-z, A-Z, 0-9, !()=+#,.-;:_ {}[], min 2 of categories (uppercase, lowercase, special char or digit)..
        /// </summary>
        public static string ErrorResponsePasswordNotValidNewRules {
            get {
                return ResourceManager.GetString("ErrorResponsePasswordNotValidNewRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password does not fit the password rules: 6-8 chars, allowed a-z, A-Z, 0-9, !()=+#,.-;:_ {}[], min. 2 of categories (uppercase, lowercase, special char or digit)..
        /// </summary>
        public static string ErrorResponsePasswordNotValidOldRules {
            get {
                return ResourceManager.GetString("ErrorResponsePasswordNotValidOldRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password failed.
        /// </summary>
        public static string ErrorResponseSavePasswordFailed {
            get {
                return ResourceManager.GetString("ErrorResponseSavePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string ErrorResponseUserIsNotActivated {
            get {
                return ResourceManager.GetString("ErrorResponseUserIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authenticated.
        /// </summary>
        public static string ErrorResponseUserIsNotAuthenticated {
            get {
                return ResourceManager.GetString("ErrorResponseUserIsNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UADM connection error.
        /// </summary>
        public static string ErrorUadmConnection {
            get {
                return ResourceManager.GetString("ErrorUadmConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current username is missing.
        /// </summary>
        public static string ErrorUsernameRequired {
            get {
                return ResourceManager.GetString("ErrorUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string LabelApplication {
            get {
                return ResourceManager.GetString("LabelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string LabelChangePassword {
            get {
                return ResourceManager.GetString("LabelChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string LabelEnvironment {
            get {
                return ResourceManager.GetString("LabelEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password 1.
        /// </summary>
        public static string LabelNewPassword1 {
            get {
                return ResourceManager.GetString("LabelNewPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password 2.
        /// </summary>
        public static string LabelNewPassword2 {
            get {
                return ResourceManager.GetString("LabelNewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string LabelOldPassword {
            get {
                return ResourceManager.GetString("LabelOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string LabelRegionOrBranch {
            get {
                return ResourceManager.GetString("LabelRegionOrBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string TitleNewPassword {
            get {
                return ResourceManager.GetString("TitleNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a branch/region.
        /// </summary>
        public static string ValidationBranchRegion {
            get {
                return ResourceManager.GetString("ValidationBranchRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        public static string ValidationCountry {
            get {
                return ResourceManager.GetString("ValidationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an environment.
        /// </summary>
        public static string ValidationEnvironment {
            get {
                return ResourceManager.GetString("ValidationEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language.
        /// </summary>
        public static string ValidationLanguage {
            get {
                return ResourceManager.GetString("ValidationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password.
        /// </summary>
        public static string ValidationNewPassword1 {
            get {
                return ResourceManager.GetString("ValidationNewPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the verification password.
        /// </summary>
        public static string ValidationNewPassword2 {
            get {
                return ResourceManager.GetString("ValidationNewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password.
        /// </summary>
        public static string ValidationPassword {
            get {
                return ResourceManager.GetString("ValidationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change is required.
        /// </summary>
        public static string ValidationPasswordChangeRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordChangeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the username.
        /// </summary>
        public static string ValidationUsername {
            get {
                return ResourceManager.GetString("ValidationUsername", resourceCulture);
            }
        }
    }
}
