#================================================================================
#   tenderordercreator makefile (AIX) 
#   13.06.2012
#   v 1.0.0
#================================================================================


#--------------------------------------------------------------------------------
# build artifact 
#--------------------------------------------------------------------------------

TARGET         = tenderordercreator.bin

#--------------------------------------------------------------------------------
# include common library versions and library depends 
#--------------------------------------------------------------------------------+

VARS_FILE      = ../makevars.inc

include $(VARS_FILE)

#---------------------------------------------------------------------------------
# source directories
#---------------------------------------------------------------------------------

# sources (seperated with blank if more than one directory)
DIR_SRCS       = . \
                 componentmanager \
                 domainmodule \
                 infrastructure \
                 infrastructure/mail \
                 infrastructure/cscclient \
                 infrastructure/purchasedbconn \
                 exceptions \
                 usecase \
                 loggerpool \
                 misc \
				 gen-cpp 

# headers (seperated with blank if more than one directory)
DIR_INCS       = $(DIR_SRCS)
                 

#--------------------------------------------------------------------------------
# libraries 
#--------------------------------------------------------------------------------
LIBS_STATIC    = $(LIBTENDER_LIB) \
                 $(LIBUTIL_LIB) \
                 $(KSCCLIENT_LIB) \
                 $(PPUNIXC_LIB) \
				 $(THRIFT_LIB)  \
				 $(THRIFTZ_LIB) \
				 $(LIBCRYPTO_LIB) \
				 $(LIBSSL_LIB)

LIBS_SHARED    = $(LOG4CPLUS_SHARED_LIBS) $(BASAR_SHARED_LIBS) $(BOOST_SYSTEM_SHARED_LIBS)\
                 $(QT_CORE_SHARED_LIBS) $(TCACCESS_SHARED_LIBS) -liconv

# additional library dirs to add with -L like -L$(LIB_DIR)
ADD_LIB_DIRS   =

ENABLE_BIG_TOC = 0

# additional compiler options like -pthread
ADD_COMP_OPTS  = -pedantic -Wno-long-long
# additional linker options like -lpthread
ADD_LINK_OPTS   =

#--------------------------------------------------------------------------------
# defines
#--------------------------------------------------------------------------------

COMMON_DEFINES =

C_DEFINES      =
ESQL_DEFINES   =
CPP_DEFINES    =

#--------------------------------------------------------------------------------
# header
#--------------------------------------------------------------------------------
# include paths
INCS = -I. \
       $(LIBTENDER_INC) \
       $(LIBUTIL_INC) \
       $(BASAR_INC) \
       $(BOOST_INC) \
       $(LOG4CPLUS_INC) \
       $(QT_INC) \
       $(KSCCLIENT_INC) \
       $(PPUNIXC_INC) \
	   $(THRIFT_INC) \
	   $(OPENSSL_INC)  \
	   $(GENCPP_INC) 

#--------------------------------------------------------------------------------
# build rules includes
#--------------------------------------------------------------------------------

BUILD_RULES_FILE = $(DEVLIB_PATH)/marathon/make/makefile.inc
include $(BUILD_RULES_FILE)
