#ifndef GUARD_TENDERBATCHPROCESSING_INFRASTRUCTURE_ACCESSOR_OMGCALCACC_H
#define GUARD_TENDERBATCHPROCESSING_INFRASTRUCTURE_ACCESSOR_OMGCALCACC_H

#include <libutil/accessor.h>

namespace tenderbatchprocessing
{
namespace infrastructure
{
namespace accessor
{
namespace omgcalc
{
	BEGIN_QUERY_BUILDER_DECLARATION( SelectOMGCalcForTransfer )
	END_BUILDER_DECLARATION

	BEGIN_QUERY_BUILDER_DECLARATION( SelectOMGCalcById )
	END_BUILDER_DECLARATION

	BEGIN_QUERY_BUILDER_DECLARATION( SelectOMGCalcByPattern )
	END_BUILDER_DECLARATION

	BEGIN_WRITE_BUILDER_DECLARATION( InsertOMGCalc)
	END_BUILDER_DECLARATION

	BEGIN_WRITE_BUILDER_DECLARATION( UpdateOMGCalc )
	END_BUILDER_DECLARATION

}
}
}
}

#endif //end GUARD_TENDERBATCHPROCESSING_INFRASTRUCTURE_ACCESSOR_OMGCALCACC_H
