#ifndef GUARD_SQLSTRINGBUILDERIMPL_H
#define GUARD_SQLSTRINGBUILDERIMPL_H
//--------------------------------------------------------------------------------------------------------//
/*! \file
*  \brief  intern interface for building SQL - statements
*  \author Roland Kiefert
*  \date   14.07.2005
*/
//--------------------------------------------------------------------------------------------------------//

//--------------------------------------------------------------------------------------------------------//
// includes
//--------------------------------------------------------------------------------------------------------//
#include "libbasar_definitions.h"
#include "sqlstringbuilderbaseimpl.h"

//--------------------------------------------------------------------------------------------------------//
// namespaces
//--------------------------------------------------------------------------------------------------------//
namespace basar
{
    namespace db
    {
        namespace aspect
        {

//--------------------------------------------------------------------------------------------------------//
// class declaration
//--------------------------------------------------------------------------------------------------------//
            /*! \brief  A class to build SQL - statements.

            This is a final class.
            This is a value class, copying is allowed, generated by the compiler */
//--------------------------------------------------------------------------------------------------------//
            class SQLStringBuilderImpl : public SQLStringBuilderBaseImpl
            {

                public:

                    ~SQLStringBuilderImpl();

                    /*! \brief solve the parameter and append the pattern to the SQL-statement. \n UnknownPropertyNameException */
                    virtual void resolve(            const VarString& pattern                            );
            };

            /*--------------------------------------------------------------------------------------------------*/
        } // aspect
    } // db
} // basar

/*--------------------------------------------------------------------------------------------------*/
#endif
