//----------------------------------------------------------------------------
/*! \file
 *  \brief  internal interface menu
 *  \author Roland Kiefert 
 *  \date   06.12.2005
 */
//----------------------------------------------------------------------------

#ifndef GUARD_LIBBASARGUIQT_ABOUTDLG_H
#define GUARD_LIBBASARGUIQT_ABOUTDLG_H

//------------------------------------------------------------------------------
#ifndef LIBBASARGUIQT_API
	#ifdef _WIN32
		#ifdef LIBBASARGUIQT_EXPORTS
			#define LIBBASARGUIQT_API __declspec(dllexport)	//!< dll exported
		#else
			#define LIBBASARGUIQT_API __declspec(dllimport)	//!< dll imported
		#endif 
	#else 
		#define LIBBASARGUIQT_API
	#endif 
#endif 

//----------------------------------------------------------------------------
#pragma warning (push)
#pragma warning(disable : 4127 4512 4481)
#include <QtWidgets/QDialog>
#include "ui_aboutdlg.h"
#pragma warning (pop)

#include <libbasarcmnutil_bstring.h>

//----------------------------------------------------------------------------
namespace basar	{
namespace gui	{
namespace qt	{

//----------------------------------------------------------------------------
/*! \brief  A class to manage the About dialog in a program. 

	This is a final class.
	This is a value class, copying is allowed, generated by the compiler */
class AboutDlg : public QDialog
{
    Q_OBJECT

public:
	/*! \brief constructor of AboutDlg
		\n     no-throw */
    LIBBASARGUIQT_API AboutDlg(QWidget *parent = 0  //!< parent window class of the application
							  );
	/*! \brief destructor of AboutDlg 
		\n     no-throw */
    LIBBASARGUIQT_API ~AboutDlg();

private slots:
	/*! \brief user clicked on docu-link in about dialog -> docu will be opened in browser 
		\n     no-throw */
    void link();
private:
    Ui::aboutdlgClass ui;							//!< gui class object
    VarString m_DocuLink;                             //!< link to application's documentation
};

//----------------------------------------------------------------------------
}	// namespace qt
}	// namespace gui
}	// namespace bassar

#endif 
