//----------------------------------------------------------------------------
/*! \file
 *  \brief  internal interface background
 *  \author Roland Kiefert 
 *  \date   12.12.2005
 */
//----------------------------------------------------------------------------

#ifndef GUARD_LIBBASARGUIQT_MAINBACKGROUND_H
#define GUARD_LIBBASARGUIQT_MAINBACKGROUND_H

//------------------------------------------------------------------------------
#ifndef LIBBASARGUIQT_API
	#ifdef _WIN32
		#ifdef LIBBASARGUIQT_EXPORTS
			#define LIBBASARGUIQT_API __declspec(dllexport)	//!< dll exported
		#else
		    #define LIBBASARGUIQT_API __declspec(dllimport)	//!< dll imported
	    #endif 
	#else 
		#define LIBBASARGUIQT_API
	#endif 
#endif

//------------------------------------------------------------------------------
#pragma warning (push)
#pragma warning(disable: 4127 4251 4512)
#include <QtWidgets/QWidget>
#include <QtGui/QImage>
#pragma warning (pop)

#include "libbasarcmnutil_bstring.h"

//------------------------------------------------------------------------------
namespace basar	{
namespace gui	{
namespace qt	{

//----------------------------------------------------------------------------
/*! \brief  A class to buil the standard background in the Qt - application with basar. 

	This is a final class.
	This is a value class, copying is allowed, generated by the compliler 
*/
class MainBackground : public QWidget
{

public:
	//! \brief images to select for showing on background
	enum ImageEnum 
	{
		PHOENIXGROUP,	//!< pharmos logo with phoenix group it
        NEUTRAL         //!< pharmos logo without phoenix group it
	};

    //! \brief enum for specifying which application type indicator is drawn
    enum ProductTypeEnum
    {
        UNKNOWN = -1,   //!< unknown / don't use indicator
        INBOUND,        //!< use inbounds indicator
        OUTBOUND,       //!< use outbounds indicator
        WAREHOUSE       //!< use warehouses indicator
    };

	/*! \brief constructor 
		\n     no-throw */
    LIBBASARGUIQT_API MainBackground();

	/*! \brief init the class. 
		\n	   no-throw */
	LIBBASARGUIQT_API void init(const VarString & rProgrammName,		//!< the application name
						        const VarString & rVersion,				//!< version string from the application
                                const ProductTypeEnum eProductType,     //!< product type
						        const ImageEnum   eImage = PHOENIXGROUP	//!< the kind of background image 
						        );
	/*! \brief init the class. 
		\n	   no-throw */
	LIBBASARGUIQT_API void init(const VarString & rProgrammName,	//!< the application name
						        const VarString & rVersion,			//!< version string from the application
						        QImage          * pImage			//!< image which is drawn in the background
						        );

	/*! \brief return minimum size. 
		\n	   no-throw */
    LIBBASARGUIQT_API QSize minimumSizeHint() const;
	/*! \brief return size. 
		\n	   no-throw */
    LIBBASARGUIQT_API QSize sizeHint() const;

protected:
	/*! \brief paint the background. 
		\n	   no-throw */
    LIBBASARGUIQT_API void paintEvent(QPaintEvent *event					//!< the event which is given
										);

private:

    void loadProductTypeImage();

	QImage		m_Background;	//!< the current image
    QImage      m_ProductTypeImage; //!< image for the product type
	VarString	m_Name;			//!< the name of the application
	VarString	m_Version;		//!< the version string from the application
    ProductTypeEnum m_ProductType;
};

}	// namespace qt
}	// namespace gui
}	// namespace bassar

#endif // GUARD_LIBBASARGUIQT_MAINBACKGROUND_H
