//----------------------------------------------------------------------------
/*! \file
 *  \brief  internal interface menu
 *  \author Roland Kiefert 
 *  \date   22.12.2005
 */
//----------------------------------------------------------------------------

#ifndef GUARD_LIBBASARGUIQT_ABOUT_H
#define GUARD_LIBBASARGUIQT_ABOUT_H


//------------------------------------------------------------------------------
#ifndef LIBBASARGUIQT_API
	#ifdef _WIN32
		#ifdef LIBBASARGUIQT_EXPORTS
			#define LIBBASARGUIQT_API __declspec(dllexport)	//!< dll exported
		#else
			#define LIBBASARGUIQT_API __declspec(dllimport)	//!< dll imported
		#endif 
	#else 
		#define LIBBASARGUIQT_API
	#endif 
#endif 

//------------------------------------------------------------------------------
class QWidget;

//------------------------------------------------------------------------------
namespace basar	{
namespace gui	
{
	namespace tie	
	{
		enum WidgetReturnEnum;
	}

	namespace qt	
	{

//----------------------------------------------------------------------------
/*! \brief  A class to define the standards in the Qt - about - dialog. 

	This is a final class.
	This is a value class, copying is allowed, generated by the compliler 
*/
class About
{
public:
	/*! \brief constructor
		\n     no-throw */
    LIBBASARGUIQT_API About		();
	/*! \brief destructor
		\n     no-throw */
    LIBBASARGUIQT_API ~About	();

	/*! \brief show the aboutdialog. 
		\n	   no-throw */
	LIBBASARGUIQT_API tie::WidgetReturnEnum	show	(QWidget *parent = 0 //!< parent window class
													);
};

//------------------------------------------------------------------------------
}	// namespace qt
}	// namespace gui
}	// namespace bassar

//------------------------------------------------------------------------------
#endif // GUARD
