//----------------------------------------------------------------------------
/*! \file
 *  \brief  internal interface statusline
 *  \author Roland Kiefert 
 *  \date   06.12.2005
 */
//----------------------------------------------------------------------------

#ifndef GUARD_LIBBASARGUIQT_STATUSLINE_H
#define GUARD_LIBBASARGUIQT_STATUSLINE_H

//------------------------------------------------------------------------------
#ifndef LIBBASARGUIQT_API
	#ifdef _WIN32
		#ifdef LIBBASARGUIQT_EXPORTS
			#define LIBBASARGUIQT_API __declspec(dllexport)	//!< dll exported
		#else
			#define LIBBASARGUIQT_API __declspec(dllimport)	//!< dll imported
		#endif 
	#else 
		#define LIBBASARGUIQT_API
	#endif 
#endif 

//------------------------------------------------------------------------------
#include "libbasar_definitions.h"

//------------------------------------------------------------------------------
class QMainWindow;
class QLineEdit;

//------------------------------------------------------------------------------
namespace basar	{
namespace gui	{
namespace qt	{

//----------------------------------------------------------------------------
/*! \brief  A class to define the standards in the Qt - statusbar. 

	This is a final class.
	This is a value class, copying is allowed, generated by the compliler 
*/
class StatusLine
{
public:
	/*! \brief constructor 
		\n     no-throw */
    LIBBASARGUIQT_API StatusLine();
	/*! \brief destructor 
		\n     no-throw */
    LIBBASARGUIQT_API ~StatusLine();

	/*! \brief init the class. 
		\n	   no-throw */
	LIBBASARGUIQT_API void init				(QMainWindow * pParent		//!< main window class from the application
											);
	/*! \brief clear the class. 
		\n	   no-throw */
	LIBBASARGUIQT_API void clear();

	/*! \brief set the user in the statusbar. 
		\n	   no-throw */
	LIBBASARGUIQT_API void setUser			(const VarString & rName	//!< the user string for the statusbar
											);
	/*! \brief set the connection in the statusbar. 
		\n	   no-throw */
	LIBBASARGUIQT_API void setConnection	(const VarString & rConn	//!< the connection string for the statusbar
											);

private:
	QLineEdit *		m_PermanentConnection;	//!< edit field containing connection
	QLineEdit *		m_PermanentUser;		//!< edit field containing user
	QMainWindow *	m_Parent;				//!< main window the statusline belongs to

};

}	// namespace qt
}	// namespace gui
}	// namespace bassar

#endif // GUARD_LIBBASARGUIQT_STATUSLINE_H
