#ifndef GUARD_LIBTENDER_INFRASTRUCTURE_ACCESSOR_SCHEDULEDDELIVERYPOSITIONSACC_H
#define GUARD_LIBTENDER_INFRASTRUCTURE_ACCESSOR_SCHEDULEDDELIVERYPOSITIONSACC_H

namespace libtender
{
namespace infrastructure
{
namespace accessor
{
namespace scheduledDelivery
{
BEGIN_QUERY_BUILDER_DECLARATION( SelectScheduledDeliveryPositionsByKey )
END_BUILDER_DECLARATION

BEGIN_AGGREGATE_QUERY_BUILDER_DECLARATION( SelectAlreadyReservedQuantity )
END_BUILDER_DECLARATION

BEGIN_WRITE_BUILDER_DECLARATION( InsertScheduledDeliveryPosition )
END_BUILDER_DECLARATION

BEGIN_WRITE_BUILDER_DECLARATION( UpdateScheduledDeliveryPosition )
END_BUILDER_DECLARATION

BEGIN_WRITE_BUILDER_DECLARATION( DeleteScheduledDeliveryPosition )
END_BUILDER_DECLARATION


} // end namespace scheduledDelivery
} // end namespace accessor
} // end namespace infrastructure
} // end namespace libtender

#endif //end GUARD_LIBTENDER_INFRASTRUCTURE_ACCESSOR_SCHEDULEDDELIVERYPOSITIONSACC_H

